### ISSUE TITLE
Huge library makes Audios angry!

### ISSUE THREAD

**Issue by mgscreativa** [libasys/audios#6]
Hi, after install Audios App on my OC, I can start music search and after a while, if I reload the page I can see a few albums but not all, so I went to my log file and found that Audios is throwing some exceptions.

```
 Fatal  index   Exception: {"Exception":"Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_audios_tracks` (`user_id`,`title`,`number`,`artist_id`,`album_id`,`length`,`file_id`,`bitrate`,`mimetype`) VALUES(?,?,?,?,?,?,?,?,?)' with params [\"martinb\", \"351 - Peque\\u00f1o siervo de un gran Dios.mp3\", 0, 21, 35, null, 1730, 0, \"audio\\\/mpeg\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'length' cannot be null","Code":0,"Trace":"#0 \/var\/www\/clients\/client1\/web2\/web\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/clients\/client1\/web2\/web\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/clients\/client1\/web2\/web\/cloud\/apps\/audios\/controller\/scannercontroller.php(390): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/clients\/client1\/web2\/web\/cloud\/apps\/audios\/controller\/scannercontroller.php(283): OCA\\Audios\\Controller\\ScannerController->writeTrackToDB(Array)\n#5 [internal function]: OCA\\Audios\\Controller\\ScannerController->scanForAudios()\n#6 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Audios\\Controller\\ScannerController), 'scanForAudios')\n#8 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Audios\\Controller\\ScannerController), 'scanForAudios')\n#9 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ScannerControll...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/clients\/client1\/web2\/web\/cloud\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/audios\/sc...')\n#13 \/var\/www\/clients\/client1\/web2\/web\/cloud\/index.php(40): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/clients\/client1\/web2\/web\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":112}    2015-08-04T19:22:06-03:00
Error   PHP     Undefined index: playtime_string at /var/www/clients/client1/web2/web/cloud/apps/audios/controller/scannercontroller.php#277 
```
##

**Comment by libasys** [comment]
Please give me some more information, what a huge library (amount of songs) is? thanks!

**Comment by mgscreativa** [comment]
It's 2358 mp3 files!

**Comment by raptwa** [comment]
I too have that problem. Total number of songs is 8000+. The app runs fin up to some 1500 songs and than stops. Pressing the refresh button always add 20 new songs.

```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_audios_tracks` (`user_id`,`title`,`number`,`artist_id`,`album_id`,`length`,`file_id`,`bitrate`,`mimetype`) VALUES(?,?,?,?,?,?,?,?,?)' with params [\"raptwa\", \"Why Worry\", 2, 431, 321, \"3:01\", 354846, 192000, \"audio\\\/mpeg\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '354846-raptwa' for key 'aa_tracks_file_user_id_idx'","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/owncloud\/apps\/audios\/controller\/scannercontroller.php(670): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/owncloud\/apps\/audios\/controller\/scannercontroller.php(558): OCA\\Audios\\Controller\\ScannerController->writeTrackToDB(Array)\n#5 [internal function]: OCA\\Audios\\Controller\\ScannerController->scanForAudios()\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Audios\\Controller\\ScannerController), 'scanForAudios')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Audios\\Controller\\ScannerController), 'scanForAudios')\n#9 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ScannerControll...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/audios\/sc...')\n#13 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66}
```
